Repository Team-InIT/AOS_inIT, pull requests merged in 2022-11, with the labels that each got.

#2 [FEAT] #1 - set bottom navi
  .idea/misc.xml
  app/src/main/java/com/swu/aos_init/presentation/ui/MainActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/alarm/AlarmFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/feed/FeedFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/search/SearchFragment.kt
  app/src/main/res/color/menu_selector_color.xml
  app/src/main/res/drawable/ic_btm_nav_alarm.xml
  app/src/main/res/drawable/ic_btm_nav_feed.xml
  app/src/main/res/drawable/ic_btm_nav_home.xml
  app/src/main/res/drawable/ic_btm_nav_mypage.xml
  app/src/main/res/drawable/ic_btm_nav_search.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_alarm.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/menu/menu_main_bottom_nav.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐸지연🐸, 🛠FEAT🛠

#4 [UI]#3 - signin view
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signin/SignInActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signin/SignInViewModel.kt
  app/src/main/java/com/swu/aos_init/presentation/util/BindingAdapter.kt
  app/src/main/res/color/selector_singin_txt.xml
  app/src/main/res/drawable-v24/img_logo_picture.png
  app/src/main/res/drawable-v24/img_logo_txt.png
  app/src/main/res/drawable/rectangle_fill_1c2e52_radius_10.xml
  app/src/main/res/drawable/rectangle_fill_e6e6e6_radius_10.xml
  app/src/main/res/drawable/rectangle_stroke_e6e6e6_radius_10.xml
  app/src/main/res/drawable/selector_signin_btn.xml
  app/src/main/res/font/pretandard_bold.ttf
  app/src/main/res/font/pretendard_extra_bold.ttf
  app/src/main/res/font/pretendard_regular.ttf
  app/src/main/res/font/pretendard_semibold.ttf
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🎨UI🎨, 🐸지연🐸

#7 [UI] #6 signup common
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signin/SignInActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/SignUpActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/SignUpViewModel.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/common/SignUpStepOneFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/common/SignUpStepTwoFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/default/SignUpDefaultStepOneFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/default/SignUpDefaultStepTwoFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/org/SignUpOrgStepOneFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/org/SignUpOrgStepTwoFragment.kt
  app/src/main/res/color/selector_signup_txt.xml
  app/src/main/res/drawable-v24/img_signup_default_active.png
  app/src/main/res/drawable-v24/img_signup_default_inactive.png
  app/src/main/res/drawable-v24/img_signup_design_active.png
  app/src/main/res/drawable-v24/img_signup_design_inactive.png
  app/src/main/res/drawable-v24/img_signup_develop_active.png
  app/src/main/res/drawable-v24/img_signup_develop_inactive.png
  app/src/main/res/drawable-v24/img_signup_org_active.png
  app/src/main/res/drawable-v24/img_signup_org_inactive.png
  app/src/main/res/drawable-v24/img_signup_plan_active.png
  app/src/main/res/drawable-v24/img_signup_plan_inactive.png
  app/src/main/res/drawable/custom_signup_progressbar.xml
  app/src/main/res/drawable/ic_signup_back.xml
  app/src/main/res/drawable/rectangle_fill_1c2e52_radius_5.xml
  app/src/main/res/drawable/rectangle_fill_e6e6e6_radius_5.xml
  app/src/main/res/drawable/selector_signup_default_btn.xml
  app/src/main/res/drawable/selector_signup_id_check_btn.xml
  app/src/main/res/drawable/selector_signup_org_btn.xml
  app/src/main/res/font/pretendard_medium.ttf
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_signup_default_step_one.xml
  app/src/main/res/layout/fragment_signup_default_step_two.xml
  app/src/main/res/layout/fragment_signup_org_step_one.xml
  app/src/main/res/layout/fragment_signup_org_step_two.xml
  app/src/main/res/layout/fragment_signup_step_one.xml
  app/src/main/res/layout/fragment_signup_step_two.xml
  app/src/main/res/navigation/signup_nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🎨UI🎨, 🐸지연🐸

#9 [Feat] #8 signup common logic
  app/build.gradle
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signin/SignInActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/SignUpActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/SignUpViewModel.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/common/SignUpStepOneFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/common/SignUpStepTwoFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/util/EditTextValidate.kt
  app/src/main/res/layout/fragment_signup_step_two.xml
  app/src/main/res/values/strings.xml
Labels: 🐸지연🐸, 🛠FEAT🛠

#12 [UI]#10 - signup default
  .gitignore
  app/.gitignore
  app/src/main/res/color/selector_signup_default_one_btn.xml
  app/src/main/res/color/selector_signup_default_one_btn_stroke.xml
  app/src/main/res/color/selector_signup_default_one_txt.xml
  app/src/main/res/drawable/rectangle_stroke_cecece_radius_10.xml
  app/src/main/res/drawable/selector_signup_default_one_btn.xml
  app/src/main/res/drawable/selector_signup_default_position_btn.xml
  app/src/main/res/drawable/selector_signup_position_design_btn.xml
  app/src/main/res/drawable/selector_signup_position_develop_btn.xml
  app/src/main/res/drawable/selector_signup_position_plan_btn.xml
  app/src/main/res/layout/fragment_signup_default_step_one.xml
  app/src/main/res/layout/fragment_signup_default_step_two.xml
  app/src/main/res/layout/fragment_signup_step_two.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🎨UI🎨, 🐸지연🐸

#13 [UI] #11 - signup org view
  app/src/main/res/layout/fragment_signup_default_step_one.xml
  app/src/main/res/layout/fragment_signup_org_step_one.xml
  app/src/main/res/layout/fragment_signup_org_step_two.xml
  app/src/main/res/values/strings.xml
Labels: 🎨UI🎨, 🐸지연🐸

#15 [Feat] #14 - signup default logic
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/SignUpActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/SignUpViewModel.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/common/SignUpStepOneFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/common/SignUpStepTwoFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/default/SignUpDefaultStepOneFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/default/SignUpDefaultStepTwoFragment.kt
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_signup_default_step_one.xml
  app/src/main/res/layout/fragment_signup_default_step_two.xml
  app/src/main/res/layout/fragment_signup_org_step_one.xml
  app/src/main/res/values/themes.xml
Labels: 🐸지연🐸, 🛠FEAT🛠

#17 [FEAT] #16 signup org logic
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/org/SignUpOrgStepOneFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/org/SignUpOrgStepTwoFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/util/EditTextValidate.kt
  app/src/main/res/layout/fragment_signup_org_step_one.xml
  app/src/main/res/layout/fragment_signup_org_step_two.xml
  app/src/main/res/values/strings.xml
Labels: 🐸지연🐸, 🛠FEAT🛠

#22 [UI] #21 - home view
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swu/aos_init/presentation/ui/home/recommend/HomeRecommendActivity.kt
  app/src/main/res/drawable-v24/img_info.png
  app/src/main/res/drawable/ic_home_back.xml
  app/src/main/res/layout/activity_home_recommend.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_belong_project.xml
  app/src/main/res/layout/item_project.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🎨UI🎨, 🐸지연🐸

#24 [FEAT] #23 - home logic
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swu/aos_init/data/response/ResponseProject.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/home/adapter/ProjectRvAdapter.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/home/adapter/ProjectVpAdapter.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/home/recommend/HomeRecommendActivity.kt
  app/src/main/res/layout/activity_home_recommend.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_belong_project.xml
  app/src/main/res/layout/item_project.xml
Labels: 🐸지연🐸, 🛠FEAT🛠

#26 [CHORE]#25 setting server
  .idea/misc.xml
  app/src/main/java/com/swu/aos_init/data/response/ServiceCreator.kt
  app/src/main/java/com/swu/aos_init/data/response/response/BaseResponse.kt
  app/src/main/java/com/swu/aos_init/data/response/response/ResponseProject.kt
  app/src/main/java/com/swu/aos_init/data/response/service/SignService.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/home/adapter/ProjectRvAdapter.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/home/adapter/ProjectVpAdapter.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/home/recommend/HomeRecommendActivity.kt
  app/src/main/res/layout/item_belong_project.xml
  app/src/main/res/layout/item_project.xml
Labels: 🐸지연🐸

#31 [FEAT]#30 - add signin sever connection
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swu/aos_init/data/request/RequestLogin.kt
  app/src/main/java/com/swu/aos_init/data/response/BaseResponse.kt
  app/src/main/java/com/swu/aos_init/data/response/ResponseLogin.kt
  app/src/main/java/com/swu/aos_init/data/service/SignService.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signin/SignInActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signin/SignInViewModel.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/default/SignUpDefaultStepTwoFragment.kt
  app/src/main/res/color/selector_signin_org_check_txt.xml
  app/src/main/res/drawable-v24/img_signin_org_checked.png
  app/src/main/res/drawable-v24/img_signin_org_unchecked.png
  app/src/main/res/drawable/selector_signin_org_btn.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐸지연🐸, 🛠FEAT🛠

#33 [FEAT]#29 - org signup server connect
  .idea/misc.xml
  app/src/main/java/com/swu/aos_init/data/request/RequestSignUpCompany.kt
  app/src/main/java/com/swu/aos_init/data/response/BaseResponse.kt
  app/src/main/java/com/swu/aos_init/data/service/SignService.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signin/SignInActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signin/SignInViewModel.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/SignUpViewModel.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/common/SignUpStepTwoFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/default/SignUpDefaultStepTwoFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/org/SignUpOrgStepOneFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/org/SignUpOrgStepTwoFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/util/BottomSheetDefaultUtil.kt
Labels: 🐸지연🐸, 🛠FEAT🛠

#34 Feat/20 wrtie project
  .idea/git_toolbox_prj.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swu/aos_init/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/home/viewmodel/OpenProjectViewModel.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/home/write/WriteProjectActivity.kt
  app/src/main/res/drawable/ic_back_white.xml
  app/src/main/res/drawable/ic_btm_nav_alarm.xml
  app/src/main/res/drawable/ic_btm_nav_feed.xml
  app/src/main/res/drawable/ic_btm_nav_home.xml
  app/src/main/res/drawable/ic_btm_nav_mypage.xml
  app/src/main/res/drawable/ic_btm_nav_search.xml
  app/src/main/res/drawable/ic_writing.xml
  app/src/main/res/layout/activity_write_project.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#38 [FIX]#36 - add event wrapper class
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signin/SignInActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signin/SignInViewModel.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/SignUpViewModel.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/common/SignUpStepTwoFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/default/SignUpDefaultStepTwoFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/sign/signup/org/SignUpOrgStepTwoFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/util/Event.kt
Labels: 🐸지연🐸, 🛠FEAT🛠

#42 [FEAT]#41 - add feed fragment layout
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swu/aos_init/data/response/feed/ResponseFeed.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/feed/FeedFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/feed/adapter/FeedAdapter.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/home/adapter/ProjectRvAdapter.kt
  app/src/main/res/color/selector_feed_txt.xml
  app/src/main/res/drawable/ic_feed_add.xml
  app/src/main/res/drawable/ic_filter_active.xml
  app/src/main/res/drawable/ic_filter_inactive.xml
  app/src/main/res/drawable/selector_filter_btn.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🎨UI🎨, 🐸지연🐸

#46 [UI] #43 - feed writing layout
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swu/aos_init/presentation/base/BaseActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/feed/FeedFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/feed/write/WritingFeedActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/util/LoadingDialog.kt
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/layout/activity_write_feed.xml
  app/src/main/res/layout/dialog_loading.xml
  app/src/main/res/values/strings.xml
Labels: 🎨UI🎨, 🐸지연🐸

#49 [UI] #48 - search tab layout
  app/src/main/java/com/swu/aos_init/presentation/ui/search/SearchFragment.kt
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
Labels: 🎨UI🎨, 🐸지연🐸

#52 [FEAT] #47 - add feed bottom sheet
  app/src/main/java/com/swu/aos_init/presentation/ui/feed/FeedFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/feed/FeedViewModel.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/feed/bottomsheet/KindBottomSheet.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/feed/bottomsheet/TechBottomSheet.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/feed/bottomsheet/TypeBottomSheet.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/feed/write/WritingFeedActivity.kt
  app/src/main/res/layout/dialog_bottom_sheet_kind.xml
  app/src/main/res/layout/dialog_bottom_sheet_tech.xml
  app/src/main/res/layout/dialog_bottom_sheet_type.xml
Labels: 🐸지연🐸, 🛠FEAT🛠

#57 Feat/56 mypage project view
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swu/aos_init/data/response/mypage/ResponseMyPageJoin.kt
  app/src/main/java/com/swu/aos_init/data/response/mypage/ResponseMyPageUpload.kt
  app/src/main/java/com/swu/aos_init/data/response/mypage/ResponseMyPageWait.kt
  app/src/main/java/com/swu/aos_init/data/response/mypage/ResponseMyPageZzim.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/mypage/MyPageJoinActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/mypage/MyPageProjectFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/mypage/MyPageUploadActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/mypage/MyPageWaitActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/mypage/MyPageZzimActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/mypage/adapter/MyPageJoinAdapter.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/mypage/adapter/MyPageUploadAdapter.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/mypage/adapter/MyPageWaitAdapter.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/mypage/adapter/MyPageZzimAdapter.kt
  app/src/main/res/layout/activity_my_page_join.xml
  app/src/main/res/layout/activity_my_page_upload.xml
  app/src/main/res/layout/activity_my_page_wait.xml
  app/src/main/res/layout/activity_my_page_zzim.xml
  app/src/main/res/layout/item_mypage_join.xml
  app/src/main/res/layout/item_mypage_upload.xml
  app/src/main/res/layout/item_mypage_wait.xml
  app/src/main/res/layout/item_mypage_zzim.xml
  app/src/main/res/values/strings.xml
Labels: 🐻혜빈🐻, 🛠FEAT🛠

#60 [FEAT] #59 feed writing logic
  app/src/main/java/com/swu/aos_init/presentation/ui/feed/FeedFragment.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/feed/bottomsheet/TechBottomSheet.kt
  app/src/main/java/com/swu/aos_init/presentation/ui/feed/write/WritingFeedActivity.kt
  app/src/main/java/com/swu/aos_init/presentation/util/BottomSheetDefaultUtil.kt
  app/src/main/res/layout/activity_write_feed.xml
Labels: 🐸지연🐸, 🛠FEAT🛠
